version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
    depends_on:
      - web-app-1
      - web-app-2
    restart: always
    networks:
      - tit-network

  web-app-1:
    build: ./web-app
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-titdb}
      - DB_PORT=${DB_PORT:-3306}
      - INSTANCE_ID=web-app-1
    volumes:
      - ./logs:/var/log/app
    restart: always
    networks:
      - tit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-app-2:
    build: ./web-app
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-titdb}
      - DB_PORT=${DB_PORT:-3306}
      - INSTANCE_ID=web-app-2
    volumes:
      - ./logs:/var/log/app
    restart: always
    networks:
      - tit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - tit-network
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  grafana:
    build: ../monitoring/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - tit-network
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=tit-demo-2024

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ../monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - tit-network
    restart: always

networks:
  tit-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  app_logs:
  nginx_logs: