global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'tit-app'
    static_configs:
      - targets: ['web-app:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s
    metrics_path: /nginx-health

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']